version: '3'

services:
  main:
    build:
      context: ./node_modules/nocker/config/nocker/runtimes/14.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: nocker-14.0/app
    environment:
      WWWUSER: '${WWWUSER}'
      NOCKER: 1
    volumes:
      - '.:/var/app'
    ports:
      - '${APP_PORT:-80}:80'
    command: npm run start
    networks:
      - nocker
  eventstore:
    image: eventstore/eventstore:20.6.1-buster-slim
    ports:
      - '${EVENTSTORE_TCP_PORT:-1113}:1113'
      - '${EVENTSTORE_HTTP_PORT:-2113}:2113'
    environment:
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: 1
      EVENTSTORE_EXT_TCP_PORT: '${EVENTSTORE_TCP_PORT}'
      EVENTSTORE_EXT_HTTP_PORT: '${EVENTSTORE_HTTP_PORT}'
      EVENTSTORE_INSECURE: 1
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 1
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 1
    networks:
      - nocker

networks:
  nocker:
    driver: bridge

